***
## [Tensor](https://pytorch.org/docs/stable/tensors.html)

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Tensor就是张量，一种容纳数据的多维容器，和多维数组类似，主要用于存储用于训练等方面的数据。

***

## [Tensor构造函数](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)
```python
torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor
```
Constructs a tensor with no autograd history (also known as a “leaf tensor”) by copying data.

通过复制数据的方式构建一个张量。

**Parameters**
* **data**(array_like) - 为tensor初始化的数据，可以是list, tuple, NumPy ndarry, scalar等类型。
* **dtype**            - 可选参数，为[torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype)中的类型，tensor的数据类型，如果为None则以参数data中的数据类型为准。
* **device**           - 可选参数，为[torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device)中的类型，tensor的运行设备，一般为"cpu"或者"cuda",如果为None时以参数data中指定的数据为准，若data无指定则为当前设备。
* **requires_grad**    - 可选参数，bool类型，为True时告诉这个tensor需要进行求导求梯度grad操作。
* **pin_memory**       - 可选参数，bool类型，为True时说明tensor会放入固定内存中，只对cpu tensor生效。

In [24]:
import torch
import numpy as np

# 零阶张量 -> 常量
tensor0d = torch.tensor(123)
print("零阶张量")
print(tensor0d)
print("-----------------------")

# 一阶张量 -> 向量 -> 一维数组
tensor1d = torch.tensor([123, 234, 567])
print("一阶张量")
print(tensor1d)
# tensor[idx] 类似数组的读数据方法
print(tensor1d[1])
print("-----------------------")

# 二阶张量 -> 矩阵 -> 二维数组
tensor2d = torch.tensor([[123, 234, 345],
                         [456, 567, 678],
                         [789, 890, 901]])
print("二阶张量")
print(tensor2d)
print(tensor2d[1])
print(tensor2d[1][2])
print("-----------------------")

# 指定dtype和device
print("指定类型和设备")
tensor1 = torch.tensor([[0.11111, 0.222222, 0.3333333]],
                        dtype=torch.float64,
                        device=torch.device('cuda:0'))
print(tensor1)
print("-----------------------")

# np.array
tensor2 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print("numpy")
print(tensor2)
print("-----------------------")

# 初始化全0tensor
tensor_all0 = torch.zeros([2,4])
print("初始化全0tensor")
print(tensor_all0)
print("-----------------------")

# 初始化全1tensor
tensor_all1 = torch.ones([2,4], dtype=torch.int32)
print("初始化全1tensor")
print(tensor_all1)
print("-----------------------")

# 随机tensor
tensor_r = torch.rand(3,4)
print("随机tensor")
print(tensor_r)
print("-----------------------")

零阶张量
tensor(123)
-----------------------
一阶张量
tensor([123, 234, 567])
tensor(234)
-----------------------
二阶张量
tensor([[123, 234, 345],
        [456, 567, 678],
        [789, 890, 901]])
tensor([456, 567, 678])
tensor(678)
-----------------------
指定类型和设备
tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)
-----------------------
numpy
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
-----------------------
初始化全0tensor
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
-----------------------
初始化全1tensor
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
-----------------------
随机tensor
tensor([[0.1463, 0.0087, 0.6814, 0.6625],
        [0.6310, 0.2867, 0.3957, 0.8345],
        [0.9719, 0.0852, 0.8702, 0.8879]])
-----------------------


***
## [Tensor属性](https://pytorch.org/docs/stable/tensor_attributes.html)
每个tensor都有torch.dtype, torch.device, torch.layout三个属性。
### torch.dtype
dtype为torch提供的数据格式。
| Data Type | dtype |
| --- | --- |
| 32-bit floating point | torch.float32 or torch.float |
| 64-bit floating point | torch.float64 or torch.double |
| 64-bit complex | torch.complex64 or torch.cfloat |
| 128-bit complex | torch.complex128 or torch.cdouble |
| 16-bit floating point | torch.float16 or torch.half |
| 16-bit floating point | torch.bfloat16 |
| 8-bit integer (unsigned) | torch.uint8 |
| 8-bit integer (signed) | torch.int8 |
| 16-bit integer (signed) | torch.int16 or torch.short |
| 32-bit integer (signed) | torch.int32 or torch.int |
| 64-bit integer (signed) | torch.int64 or torch.long |
| Boolean | torch.bool |
### torch.device
device为一个tensor所属或者将要部署的设备。

device包括一个设备类型（通常是"cpu"或者"cuda"，还可以是"mps","xpu","xia","meta"）和设备的序号。

In [20]:
torch.device('cuda:0') #序号为0的cuda gpu设备

device(type='cuda', index=0)

In [21]:
torch.device('cpu') #cpu

device(type='cpu')

In [22]:
torch.device('cuda') #当前cuda设备

device(type='cuda')

In [23]:
torch.device('cuda', 0)

device(type='cuda', index=0)

### torch.layout
layout表示tensor的内存布局，目前pytorch支持torch.strided和torch.sparse_coo即顺序存储和离散存储

***
## tensor基础运算
### 1. 加法

In [44]:
import torch

a = torch.tensor([[1, 2, 3], [2, 3, 4]])
b = torch.tensor([[3, 4, 5], [4, 5, 6]])
c = torch.tensor([5, 6, 7])

d1 = a + b
d2 = torch.add(a, b)
d3 = a.add(b)
# 这几个Tensor加减乘除会对c自动进行Broadcasting
d4 = a + c
d5 = torch.add(b, c)
d6 = c.add(b)
print(d1)
print(d2)
print(d3)
print(d4)
print(d5)
print(d6)

tensor([[ 4,  6,  8],
        [ 6,  8, 10]])
tensor([[ 4,  6,  8],
        [ 6,  8, 10]])
tensor([[ 4,  6,  8],
        [ 6,  8, 10]])
tensor([[ 6,  8, 10],
        [ 7,  9, 11]])
tensor([[ 8, 10, 12],
        [ 9, 11, 13]])
tensor([[ 8, 10, 12],
        [ 9, 11, 13]])


### 2. 减法

In [45]:
a = torch.tensor([[3, 4, 5], [2, 3, 4]])
b = torch.tensor([[3, 2, 1], [4, 5, 6]])

c1 = a - b
c2 = torch.sub(a, b)
c3 = a.sub(b)
print(c1)
print(c2)
print(c3)

tensor([[ 0,  2,  4],
        [-2, -2, -2]])
tensor([[ 0,  2,  4],
        [-2, -2, -2]])
tensor([[ 0,  2,  4],
        [-2, -2, -2]])


### 3. 乘法

In [38]:
a = torch.tensor([[1, 2, 3], [2, 3, 4]])
b = torch.tensor([[3, 4, 5], [4, 5, 6]])

c1 = a * b
c2 = torch.mul(a, b)
c3 = a.mul(b)
print(c1)
print(c2)
print(c3)

tensor([[ 3,  8, 15],
        [ 8, 15, 24]])
tensor([[ 3,  8, 15],
        [ 8, 15, 24]])


### 4. 除法

In [54]:
a = torch.tensor([[6, 2, 3], [2, 3, 4]])
b = torch.tensor([[3, 4, 5], [4, 5, 6]])

c1 = a / b
c2 = torch.div(a, b)
c3 = a.div(b)
print(c1)
print(c2)
print(c3)
print("dtype of a  " + str(a.dtype))
print("dtype of c1 " + str(c1.dtype))

tensor([[2.0000, 0.5000, 0.6000],
        [0.5000, 0.6000, 0.6667]])
tensor([[2.0000, 0.5000, 0.6000],
        [0.5000, 0.6000, 0.6667]])
tensor([[2.0000, 0.5000, 0.6000],
        [0.5000, 0.6000, 0.6667]])
dtype of a  torch.int64
dtype of c1 torch.float32


### 5. 点积

In [49]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])

c1 = torch.dot(a, b)
c2 = a.dot(b)
print(c1)
print(c2)

tensor(26)
tensor(26)


### 6. 矩阵相乘

In [79]:
# 2维矩阵
d1_1 = torch.tensor([[4]])
d1_2 = torch.tensor([[8]])
d1x2 = torch.tensor([[1, 2]])
d2x1 = torch.tensor([[3], [4]])
d2_1 = torch.tensor([[1, 2], [3, 4]])
d2_2 = torch.tensor([[5, 6], [7, 8]])

r1 = d1_1 @ d1_2                # dot product
r2 = torch.mm(d1_1, d1x2)       # 1x1 and 1x2
# r3 = torch.matmul(d1_1, d2x1) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1 and 2x1)
# r3 = torch.matmul(d1x2, d1x2) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)
# r3 = torch.matmul(d2x1, d2x1) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x1)
r4 = d1x2 @ d2x1                # 1x2 and 2x1
r5 = d1x2.mm(d2_1)              # 1x2 and 2x2
# r6 = d2x1.matmul(d2_1)        # RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x2)
r7 = d2_1 @ d2_2                # 2x2 and 2x2
print(r1)
print(r2)
print(r4)
print(r5)
print(r7)

tensor([[32]])
tensor([[4, 8]])
tensor([[11]])
tensor([[ 7, 10]])
tensor([[19, 22],
        [43, 50]])


### 7. 幂运算

In [75]:
a = torch.tensor([[1, 2], [3, 4]])

b = a.pow(2)
c = a ** 2
print(b)
print(c)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


### 8. 开方

In [80]:
a = torch.tensor([[1, 2], [3, 4]])
b = a.pow(2)

c = b.sqrt()
d = b ** (0.5)
e = b.rsqrt()
print(c)
print(d)
print(e)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 0.5000],
        [0.3333, 0.2500]])


### 9. 指数和对数