***
## [Tensor](https://pytorch.org/docs/stable/tensors.html)

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Tensor就是张量，一种容纳数据的多维容器，和多维数组类似，主要用于存储用于训练等方面的数据。

***

## [Tensor构造函数](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)
```python
torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor
```
Constructs a tensor with no autograd history (also known as a “leaf tensor”) by copying data.

通过复制数据的方式构建一个张量。

**Parameters**
* **data**(array_like) - 为tensor初始化的数据，可以是list, tuple, NumPy ndarry, scalar等类型。
* **dtype**            - 可选参数，为[torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype)中的类型，tensor的数据类型，如果为None则以参数data中的数据类型为准。
* **device**           - 可选参数，为[torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device)中的类型，tensor的运行设备，一般为"cpu"或者"cuda",如果为None时以参数data中指定的数据为准，若data无指定则为当前设备。
* **requires_grad**    - 可选参数，bool类型，为True时告诉这个tensor需要进行求导求梯度grad操作。
* **pin_memory**       - 可选参数，bool类型，为True时说明tensor会放入固定内存中，只对cpu tensor生效。

In [18]:
import torch
import numpy as np

# 零阶张量 -> 常量
tensor0d = torch.tensor(123)
print("零阶张量")
print(tensor0d)
print("-----------------------")

# 一阶张量 -> 向量 -> 一维数组
tensor1d = torch.tensor([123, 234, 567])
print("一阶张量")
print(tensor1d)
# tensor[idx] 类似数组的读数据方法
print(tensor1d[1])
print("-----------------------")

# 二阶张量 -> 矩阵 -> 二维数组
tensor2d = torch.tensor([[123, 234, 345],
                         [456, 567, 678],
                         [789, 890, 901]])
print("二阶张量")
print(tensor2d)
print(tensor2d[1])
print(tensor2d[1][2])
print("-----------------------")

# 指定dtype和device
print("指定类型和设备")
tensor1 = torch.tensor([[0.11111, 0.222222, 0.3333333]],
                        dtype=torch.float64,
                        device=torch.device('cuda:0'))
print(tensor1)
print("-----------------------")

# np.array
tensor2 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print("numpy")
print(tensor2)
print("-----------------------")

# 初始化全0tensor
tensor_all0 = torch.zeros([2,4])
print("初始化全0tensor")
print(tensor_all0)
print("-----------------------")

# 初始化全1tensor
tensor_all1 = torch.ones([2,4], dtype=torch.int32)
print("初始化全1tensor")
print(tensor_all1)

零阶张量
tensor(123)
-----------------------
一阶张量
tensor([123, 234, 567])
tensor(234)
-----------------------
二阶张量
tensor([[123, 234, 345],
        [456, 567, 678],
        [789, 890, 901]])
tensor([456, 567, 678])
tensor(678)
-----------------------
指定类型和设备
tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)
-----------------------
numpy
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
-----------------------
初始化全0tensor
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
-----------------------
初始化全1tensor
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


***
## [Tensor属性](https://pytorch.org/docs/stable/tensor_attributes.html)
每个tensor都有torch.dtype, torch.device, torch.layout三个属性。
